### index books
GET http://localhost:3000/books

### show book
GET http://localhost:3000/books/4

### create new book
POST http://localhost:3000/books
content-type: application/json

{
  "title": "Test",
  "rating_out_of_five": 1,
  "summary": "Test",
  "book_image": "Test",
  "author_id": 
}

### update book
PATCH http://localhost:3000/books/1
content-type: application/json

{
  "author_id": 2
}

### delete book
DELETE http://localhost:3000/books/5



######## author requests ########

### create new author
POST http://localhost:3000/authors
content-type: application/json

{
  "name": "Ruth Ware",
  "age": 45,
  "genre": "Psychological crime thriller"
}